version: "3.8"

networks:
  apigateway_system_network:
    external: true

services:
  post_comment_service: 
    volumes:
      - ./postgres-data:/var/lib/postgresql
    env_file:
      - ./.env.prod
    hostname:
      post_comment_service 
    networks:
      - apigateway_system_network
  
  post_comment_db:
    env_file:
      - ./.env.prod
    hostname:
      post_comment_db 
    networks:
      - apigateway_system_network